ecsyjs/ecsy

build/ecsy.d.ts, package.json
Adds typescript definitions to the package and package definition.
=> Add Typescript Definitions

examples/canvas/components.js, examples/canvas/systems.js, examples/norender/umd/systems.js, package.json, test/unit/entity.test.js, test/unit/system.test.js
Add more source dirs to the lint command. Delint the codes.
=> Lint more of the code

build/ecsy.d.ts, build/ecsy.js, build/ecsy.module.js, src/Entity.js, src/EntityManager.js, test/unit/entity.test.js
As part of the decision to adopt `TagComponent`
=> Remove tags functionality

src/CreateComponent.js, test/unit/createcomponent.test.js
=> Fix #37 copy, reset and clear are not implemented as nop when type is not defined

docs/api/README.md, examples/norender/index.html, src/SystemManager.js, src/World.js, test/unit/system.test.js
=> Implement world.getSystem(S) and world.getSystems() 

examples/ball-example/babylon/systems.mjs, examples/ball-example/three/systems.mjs, examples/canvas/systems.js, examples/factory/index.html, examples/norender/index.html, src/Entity.js, src/System.js, test/unit/system.test.js
https://github.com/fernandojsg/ecsy/issues/71
=> New syntax for queries and reactive systems

src/System.js, test/unit/system.test.js
before:
```
changed: [Foo, Bar]
=>
query.changed.foo.forEach
query.changed.bar.forEach
```
now
```
changed: [Foo, Bar]
=>
query.changed.forEach(/* changed foo or bar */)
```
=> Fix new syntax for changed with array of components

examples/index.html, index.html
Fixes #86 and #85 
Going simple as possible, I'd probably try to work on some simple background animation (with circles, lines or so) with @feiss, but in the mean time we have something at least
=> Added landing page and example page

examples/ball-example/babylon/index.html
We can do better by directly using instances which are far better for this scenario but this one will at least use geometry batching ;)
=> Improve Babylon.js example #105

index.html
Fixes https://github.com/MozillaReality/ecsy/issues/110
=> Fix link on the main page

examples/ball-example/babylon/index.html, examples/ball-example/babylon/systems.mjs
Now using instances which allows us to run smoothly :)
=> Using Babylon.js instances :)

src/RemoteDevTools/index.js, src/SystemManager.js, src/World.js, src/polyfills.js
Fixes #130 
Not the tidiest "polyfill" (more just a "graceful fallback for node" really), but this appears to be all that's presently needed to use ecsy in either environment.
=> Polyfills for node env

src/System.d.ts
Just a little PR to add 'world' member to System.d.ts to fix intellisense error when using this.world into System object.
=> Add world to System.d.ts

docs/api/classes/world.md, docs/api/interfaces/options.md, src/EntityManager.js, src/World.d.ts, src/World.js, test/unit/entity.test.js
The only implemented option so far is `entityPoolSize`.
=> Added options to the World

benchmarks/helpers/components.js, benchmarks/objectpool.bench.js, src/Component.js, src/ComponentManager.js, src/Entity.js, src/EntityManager.js, src/ObjectPool.js, test/unit/objectpool.test.js
`.reset()` has better performance with object pooling.
=> Component schema pooling with reset

README.md, benchmark_result.json, benchmarks/browser.js, benchmarks/components.bench.js, benchmarks/entities.bench.js, benchmarks/helpers/components.js, benchmarks/index.html, benchmarks/index.js, benchmarks/objectpool.bench.js, benchmarks/world.bench.js, package-lock.json, package.json, rollup.config.js, src/DummyObjectPool.js, src/Entity.js, src/EntityManager.js, src/ObjectPool.js, src/World.js, src/index.js, test/unit/objectpool.test.js
=> Benchmarks

src/Component.d.ts, src/Types.d.ts, src/Types.js
This PR adds a type for a PropType or PropTypeDefinition's default value and proper copying and cloning of types with a null/undefined default value.
=> Handle component property default values correctly

src/Component.js, src/ComponentManager.js, src/Entity.js, src/EntityManager.js, src/System.js, src/SystemManager.js, src/WrapImmutableComponent.js, test/unit/ComponentManager.test.js, test/unit/system.test.js
Instead of index the components by its constructor name, it's using a incremental id (#203)
Added a test to register two components with the same class name https://github.com/MozillaReality/ecsy/commit/c821b5209131184066eb68f2c1bb5b665421ad21
=> Remove usage of Component.name in favor of a incremental id

test/unit/entity.test.js
=> Fix and enable Entity tests

src/World.js
Fixes #223 and https://github.com/MozillaReality/ecsy-three/issues/21
=> Change elapsed time and delta if no values are provided

test/unit/stats.test.js
I think a PR got merged that wasn't up to date with `dev` and a failing test got introduced.
=> Fix Stats test

site/examples/canvas/index.html
I was playing with ECSY + TypeScript for my [_wannabe_ networked ecs](https://github.com/endel/ecs) and the compiler screamed at me because of the extra parameter :)
=> fixes .set() to use only 2 arguments

src/ComponentManager.js, src/World.js
Needed some ";"s after return statements
=> Fix linting for hasRegisteredComponent PR
