ecsyjs/ecsy

src/System.js, src/SystemManager.js, test/unit/system.test.js
Implements https://github.com/fernandojsg/ecsy/issues/28
Some comments:
- The check of this constrains is being done in `canExecute` by the system manager when looping through the systems instead of doing it in the `System.execute` so users don't need to call `super` on every  `execute` implementation. As you are not expected to call `execute` by yourself directly anyway.
- This can be replace in the future, if we feel like implement these: filters https://github.com/fernandojsg/ecsy/issues/31 and a generic `minimum` number of items in order to run `execute` https://github.com/fernandojsg/ecsy/issues/32 but I believe currently this could do the work and just put these two issues on hold until we find the need for them
=> Include mandatory attribute on queries, fixes #28

examples/canvas/index.html, examples/canvas/systems.js, examples/norender/index.html, ideas.md, src/ComponentManager.js, src/Query.js, src/System.js, src/World.js
Removing singleton functionality without using queries at all, just accessing the entity we created attached to `world.entity` (just for the sake of taking advantage of having world instance on the system, but it could be defined somewhere else).
In any case we agreed that singleton as it's implemented currently should change in this direction.
We could decide later if to include helper functions as in https://github.com/fernandojsg/ecsy/pull/39 as I expect this pattern to be used a lot
=> Remove singleton functionality

src/EntityManager.js, src/Query.js, src/QueryManager.js, src/System.js, test/unit/system.test.js
Because it's currently broken because of the references from `system.queries[].entity = query.entity`
=> Remove `single` functionality

examples/factory/index.html, package-lock.json, package.json, src/Entity.js, src/EntityManager.js, test/unit/entity.test.js, test/unit/system.test.js
Fixes #40 
Basically when doing a referred removing of a component, it won't be available on the entity as part of the `getComponent()` call as it's not a "alive" component, so we can prevent people from doing `getMutableComponent` on it and have side effects on other systems.
Instead the component is moved to a `_componentsToRemove` list and it will be cleaned at the end of the frame.
So if we have a `onComponentRemoved` query event list, we will do it this way:
```javascript
this.events.myEntities.removed.forEach(entity => {
entity.getRemovedComponent(Component) // do whatever with the component
entity.getComponent(Component) // This will return undefined
});
```
I'm not sure if it's good idea to introduce `getRemovedComponent` or just have a 
```js
getComponent(Component, true /* …
```
=> Fix #40 deferred removal/add component cycle issue

src/System.js, src/SystemManager.js, test/unit/system.test.js
As discussed in: https://github.com/fernandojsg/ecsy/issues/48
TL;DR
```javascript
class SystemA extends System {
execute() {
var entities = this.queries.entities;
for (var i = 0; i < entities.length; i++) {
entities[i].remove(true);
}
}
}
SystemA.queries = {
entities: {
components: [FooComponent]
}
};
```
=> Move queries definition to static

src/RemoteDevTools/index.js, src/SystemManager.js, src/World.js, src/polyfills.js
Reverts MozillaReality/ecsy#132
@Nebual I just noticed that using the `require(perf_hooks)` will cause `module not found` on all the examples and related code. 
We should try to find a different solution that doesn't break that.
=> Revert "Polyfills for node env"

src/World.d.ts
Fix typescript definition issue on World.registerComponent() when adding attributes
=> Add attributes to World.registerSystem typescript definition

docs/manual/Getting-started.md
Fix typo in getting started example code
query ... .result should be query ... .results
=> Getting Started doc typo

src/SystemManager.js, test/unit/SystemManager.test.js
Instead of checking for systems with the same (constructor) name, this change checks for the same constructor, i.e. an `instanceof` check. The problem with the previous approach is that a minification system like `terser` would mangle the class name, now with potentially overlapping system names. Which is perfectly valid in a modern modules-based code base, as the name under which the class is imported by the consumer manners, not under which it is defined within the imported module.
=> Fix duplicate system name check

src/EntityManager.js
If a user calls `addComponent` but the component type already exists on the entity, `entityAddComponent` will early out and ignore any `values` passed to `addComponent`. This adds a warning if this happens, so that it's easier to track down why the component value doesn't match what is provided to `addComponent`.
=> Warn if entityAddComponent is a no op

src/RemoteDevTools/index.js, src/SystemManager.js, src/Utils.js, src/World.js, test/helpers/common.js, test/unit/ComponentManager.test.js, test/unit/SystemManager.test.js, test/unit/entity.test.js, test/unit/entitymanager.test.js, test/unit/system.test.js, test/unit/systemstatecomponents.test.js
- Added `hasWindow` to detect if `window` is defined
- Added `now()` that will fallback to  `Date.now()` if `performance` is not defined
- Fix `remoteDevtools`
- Fix tests and remove `tests/common.js` with the previous globals hook
Should fix #156 and #130
=> Include "window" checker and performance.now() 'polyfill' to fix node usage

examples/index.html
I decided that to implement url hashes to point to the different demos it's best to generate the list programmatically so we can easily add events to the links.
The alternative would be to add a name attribute to the links and iterate through them that way, that would have the advantage that not having js wouldn't break the site, but since the site is there to demo a javascript library I don't think that's a concern.
This mirrors the way the example page of threejs is set up as mentioned in #94
=> generate example list procedurally and use url hash for different demos

src/SystemManager.js, test/unit/system.test.js
Throws an error if the system does not extends `System` class
=> Check system on `registerSystem`

examples/index.html
What the title says, as proposed in #171
=> add the "selected" class to the selected example link, underlining it

src/System.d.ts, src/World.d.ts
I added the System constructor to the type definition file in order to be able to call it in inheriting systems. Without this change, inheriting systems cannot specify a constructor themselves in Typescript because it could only call a default super constructor.
Example:
class MySystem extends System {
private myCustomNumber: number;
constructor(world: World, attributes?: object) {
super(world, attributes); // <-- Compiler error because System's constructor is not specified in type definition
this.myCustomNumber = attributes?.myCustomNumber;
}
}
As soon as i want to provide custom data to *MySystem* (*myCustomNumber* in the example above) by putting this data into *attributes*, i have to specify a constructor in MySystem.
=> added constructor to System type definition

src/World.d.ts
Just like the title says.
It adds the missing typescript definition for World.unregisterSystem();
=> Add unregisterSystem TS definition into World

package-lock.json, package.json, test/unit/CreateComponentClass.test.js, test/unit/createtype.test.js, test/unit/system.test.js
We're using a pretty outdated version of ava. I've updated it to the latest version which has fixes for source maps and a much better experience when debugging.
https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-chrome-devtools.md
=> Update ava to 3.9.0

site/docs/manual/Architecture.md
`getComponent(Component)` was missing `)` at line 393.
=> Fix typo in Architecture.md

src/Component.d.ts, src/World.d.ts
- `ComponentProps<P>` was sorta unnecessary and confusing so I removed it. I would still like to know if there's something else that should be done here based on this issue: https://github.com/MozillaReality/ecsy/issues/199
- `world.execute(delta: number, time: number):void` should be `world.execute(delta?: number, time?: number):void`
I'll add more if I find them soon.
=> Fix a few typescript definitions

src/Component.d.ts, src/Entity.d.ts, src/System.d.ts, src/SystemStateComponent.d.ts, src/TagComponent.d.ts, src/World.d.ts
This PR is based on the work by @krazyjakee in #205. I've tried to get typechecking working properly for all component props with the minimal boilerplate.
This is the result:
```typescript
// Note you must pass TestComponent (the type of your component) as the generic type
// for props to be typed correctly.
class TestComponent extends Component<TestComponent> {
// If you are using strict typing you will need to use ! (non-null assertion operator)
// or ? (optional property). Default properties are set in the constructor for you based on
// the type of the property or user defined default
boolProperty!: boolean; 
optionalNumberProperty?: number;
static schema = {
boolProperty: { type: Types.Boolean },
optionalNumberProperty: { type: Types.Number, default: undefined }
};
}
// Creating a …
```
=> Clean up typings related to component props

src/Types.js
The arrayCopy method copies values from the dest array to the dest array instead of from the src array to the dest array.
=> Fix the copyArray method

package-lock.json, package.json, rollup.config.js, site/docs/manual/Architecture.md, src/Entity.js, src/EntityManager.js
I saw a few `@todo` comments in the code about this so thought I would have a go at implementing something.
I thought this change made sense as CommonJS users can have `process.env.NODE_ENV` controlled by Webpack/Parcel/Rollup to have debug code automatically removed in a production build similar to React. UMD/ES Module users get a similar experience by switching between the unminified and minified builds.
Going forward it means ECSY can start to add more debug code to functions for better DX but can keep bundle size low.
=> Replace DEBUG with process.env.NODE_ENV

src/World.d.ts
Currently the types for World.getSystem() say it returns a generic System.
This updates the types to clarify that it returns the type of System requested.
=> Update types for World.getSystem() to return the type of System requested

package-lock.json, site/examples/ball-example/three/index.html, src/System.js, src/Utils.js, test/unit/Component.test.js, test/unit/Queries.test.js, test/unit/system.test.js
Based on the proposal by @zeddic in https://github.com/MozillaReality/ecsy/issues/215 to fix the minification issues.
- It fixes the `Utils.queryKey` function to use `Component._typeId` instead of names, so we don't rely on names anymore other than to throw error or logs.
- We assign the `_typeId` when registering the component, the proposal to use `getTypeId()` and create the id if it doesn't exist, and otherwise just return it has a perf overhead instead of accessing a variable. To solve that I forced the components to be registered before the systems, otherwise an error will be thrown.
- Added tests
=> Fix query collision

src/System.d.ts
Developers specify Component constructors here, not component instances.
=> Fix types for System's queries changed option

src/Entity.d.ts, src/Entity.js, test/unit/entity.test.js
Some small changes to help with TypeScript development
* The rationale for this is that `getComponent` could already return a readonly removed component so this should too
=> Return more readonly components

site/docs/manual/Architecture.md, site/docs/manual/Getting-started.md
Addresses some missing documentation as described here: https://github.com/MozillaReality/ecsy/issues/165
=> Fixes #165, added missing docs

src/Entity.d.ts
The undefined union type is technically correct, but makes it really annoying to use in strict mode and there are many other benefits to be gained in strict mode. I think we should try to use the the system query to determine if the entity has the component and only use the undefined union type when we don't know. There may not be a way to do this in typescript though.
=> Remove undefined from getComponent type

src/ComponentManager.js, src/World.d.ts, src/World.js
The goal here is to be able to check whether a component has already been registered to the world before adding it, which can be helpful when different init sequences rely on the same components.
=> Added hasRegisteredComponent to World and ComponentManager

package-lock.json, package.json, site/examples/canvas/components.js, site/examples/canvas/math.js, site/examples/canvas/systems.js, src/Component.js, src/ComponentManager.js, src/EntityManager.js, src/EventDispatcher.js, src/Query.js, src/RemoteDevTools/index.js, src/System.js, src/SystemManager.js, src/Types.js, src/World.js, src/WrapImmutableComponent.js, src/index.js, test/helpers/components.js, test/unit/Component.test.js, test/unit/ComponentManager.test.js, test/unit/Queries.test.js, test/unit/SystemManager.test.js, test/unit/createtype.test.js, test/unit/entity.test.js, test/unit/entitymanager.test.js, test/unit/objectpool.test.js, test/unit/stats.test.js, test/unit/system.test.js, test/unit/systemstatecomponents.test.js
I think vscode is using prettier 2.0 and I've been running into some issues when reformatting code. So I've upgraded us to prettier 2.0 and fixed all the linting errors.
The prettier 2.0 changelog:
https://prettier.io/blog/2020/03/21/2.0.0.html
tldr; they like trailing commas and parens around single parameter arrow functions now.
=> Upgrade prettier and fix linting

src/Entity.d.ts, src/System.d.ts
`getComponent`, `getRemovedComponent`, and `getMutableComponent` now use optional return types. This lets you use the `entity.getComponent!(MyComponent)` syntax when using Typescript's strict mode instead of `entity.getComponent(MyComponent) as MyComponent`.
=> Make getComponent use an optional return type

src/EntityManager.js, test/unit/entitymanager.test.js
When entity are destroyed, either by calling `removeAllEntities` or `Entity.remove()`, the component don't get disposed. This is because `removeEntity()` is called first, clearing the components list whem the pool calls `entity.reset()`.
=> Fix entity not calling `dispose` on components when removed

src/SystemStateComponent.js, src/TagComponent.js
When loading the library from unpkg, this isn't a problem because it knows how to serve the files [even without extensions](https://unpkg.com/ecsy@0.4.1/src/Component.js?module). But when importing from a local file tree, most file servers will respond with a 404.
.d.ts files need not be fixed because TypeScript imports work differently. I also haven't fixed any files in the test folder as I assume these are intended to run in node and not be imported in the browser.
=> Add .js extensions to imports

src/World.d.ts
Like `registerComponent` argument must be a component constructor, not an instance.
=> Fix wrong hasRegisteredComponent type

src/System.d.ts, src/World.d.ts
Hi,
This is a super simple PR introducing:
* `<Entity>` parametrization in the declaration of `World`
* `<Entity>` parametrization is the declaration of the class `System`.
When creating a custom entity, all typings are lost (in favor of the base `Entity` class) in `createEntity` and inside inherited systems. It can make the framework a bit unpleasant to use, either because you need to cast first to `unknown`, or because you need to create an intermediate system class.
=> typescript: parametrize World and System over Entity
